#!/bin/sh
set -eu

repository_root=$(git rev-parse --show-toplevel)
cd "$repository_root"

git diff --cached --no-renames --name-only --diff-filter=ACMRD \
    | sh scripts/git-hooks/generate-project.sh
